# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeliveryPassa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DeliveryPassa
    pod 'Firebase/Core', '~> 5.19.0'
    pod 'Firebase/Messaging', '~> 5.19.0'
    pod 'React', :path => '../node_modules/react-native'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

# Third party deps podspec link
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  target 'DeliveryPassa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  end

  target 'DeliveryPassaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DeliveryPassa-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DeliveryPassa-tvOS

end
